### ISSUE TITLE
example: create a pions <-> flutter-webrtc example

### ISSUE THREAD

**Issue by backkem** [pion/example-webrtc-applications#10]
Create an example connecting pions with [flutter-webrtc](https://github.com/cloudwebrtc/flutter-webrtc).

cc @gedw99

**Comment by joeblew99** [comment]
@Sean-Der any updates on this. I am also working on this and dont want to overlap work.

**Comment by anilthummar** [comment]
Hello Everyone ,
can we set up personal server with pion webrtc ?
i am getting error like below 
**{
I/flutter ( 8210): [Ion::Client] DEBUG: leave reject: error =>transport error
I/flutter ( 8210): [protoo-client] DEBUG: close()
I/flutter ( 8210): [protoo-client] DEBUG: constructor()
I/flutter ( 8210): [protoo-client] DEBUG: constructor() [url:https://meet.cynod.live/html5client/join?peer=bb48fd89-045a-47b8-b3bc-9761e21cde9c]
}**

**Comment by Sean-Der** [comment]
This is done!

[sfu-ws](https://github.com/pion/example-webrtc-applications/tree/master/sfu-ws) is a many-to-many conferencing demo. In the flutter we have an example applications that works just like the index.html
