### ISSUE TITLE
Not contain package github.com/pion/example-webrtc-applications/play-from-disk-h264

### ISSUE THREAD

**Issue by katepangLiu** [pion/example-webrtc-applications#106]
### Your environment.
  - Version: *Release or SHA*
  - Browser: *include version*
  - Other Information - *stacktraces, related issues, suggestions how to fix, links for us to have context*

### What did you do?

```
go get github.com/pion/example-webrtc-applications/play-from-disk-h264
```

### What did you expect?
Download play-from-disk-h264

### What happened?
```
go get github.com/pion/example-webrtc-applications/play-from-disk-h264
go: downloading github.com/pion/example-webrtc-applications v1.0.0
go get: module github.com/pion/example-webrtc-applications@upgrade found (v1.0.0), but does not contain package github.com/pion/example-webrtc-applications/play-from-disk-h264
```

**Comment by katepangLiu** [comment]
On the other hand, 
why we put play-from-disk in /pion/webrtc/examples, but play-from-disk-h264 in /pion/example-webrtc-applications?

**Comment by Sean-Der** [comment]
Thanks for catching that @katepangLiu I fixed the instructions!
