### ISSUE TITLE
SFU - WS Multiple Rooms

### ISSUE THREAD

**Issue by oddimportance** [pion/example-webrtc-applications#110]
Enormous thanks to all who contributed to developing these wonderful Pion-webRTC applications.

I'm experimenting with SFU-WS to develop a video conferencing tool.

Although things work like a charm, I'm clueless about how to run multiple conferences (like we know from Microsoft Teams or Zoom). Here is an example of what I'm trying to do:

Room 1: https://localhost:7676/?room-id=12345

Participants of room 1 = A, B, C, D

Room 2: https://localhost:7676/?room-id=67890

Participants of room 2 = E, F, G, H

I can imagine that a static session-id must be passed to

peerConnection, err := webrtc.NewPeerConnection(webrtc.Configuration{})

However, all my efforts/approaches have failed.

Any help would be immensely appreciated.

**Comment by Sean-Der** [comment]
Hi @oddimportance 

You should start a project under your GitHub profile! I am happy to review the code you have so far and suggest any changes.

I would also see if something like [LiveKit](https://livekit.io/) could fit your needs. If you are building conference like functionality it might hit your use cases faster.

I am also available on [Slack](https://pion.ly/slack) if you have any questions. thanks for using Pion!
