### ISSUE TITLE
Trying to run the janus video room sample results in failure

### ISSUE THREAD

**Issue by RaniRaven** [pion/example-webrtc-applications#112]
I am following the sample code in the example of janus-gateway/video-room.
I am using docker desktop on windows running a janus docker made by :
**linagora/janus-gateway** - this is taken directly by pulling from docker hub.
I am getting the following failure :
[ERR] [dtls.c:janus_dtls_retry:970] [6589176714686217] DTLS taking too much time for component 1 in stream 1...
No WebRTC media anymore
[6589176714686217] WebRTC resources freed
Detaching handle from JANUS VideoRoom plugin
No WebRTC media anymore
[WSS-0x7ff810005000] Destroying WebSocket client
Cleaning up handle 6589176714686217...
[6589176714686217] WebRTC resources freed
[6589176714686217] Handle and related resources freed
Cleaning up session 4435782097383298...

No idea how to debug this, and there is too little information from the code, or Janus-Gateway about what is causing this problem.

I noted lately that a lot are getting those failures and I wonder what is happening exactly.

Would appreciate any help.

**Comment by Sean-Der** [comment]
Hi @RaniRaven 

Sorry I didn't see this earlier. Were you able to figure out your issue? If not I am available [Slack](https://pion.ly/slack) to help debug.
