### ISSUE TITLE
when i use demo: rtp-to-webrtc  i can not play stream

### ISSUE THREAD

**Issue by czk630597526** [pion/example-webrtc-applications#113]
I just want play h264,and I send h264 stream to this demo,in website,I can not see stream.
And this h264 stream is correct,I just send this stream to vlc.
How can I solve this problem?

in chrome://webrtc-internals
framesDecoded | 0
keyFramesDecoded | 36
framesDropped | 3534
totalDecodeTime | 0

**Comment by Sean-Der** [comment]
Hi @czk630597526 

Did you replace all occurrences of `VP8` with `H264` in the main.go?

Did you run the ffmpeg command in the README?

Can you share your diff of the main.go and the ffmpeg command you ran?
