### ISSUE TITLE
how use webrtc Establish a kcp p2p/E2E connection and communicate

### ISSUE THREAD

**Issue by hktalent** [pion/example-webrtc-applications#117]
how use webrtc Establish a kcp p2p/E2E connection and communicate

**Comment by Sean-Der** [comment]
Hey @hktalent 

WebRTC doesn't support KCP. You can only use RTP over SRTP or SCTP over DTLS.

thanks!

**Comment by hktalent** [comment]
> You could possibly send KCP over DataChannels? If you start a repo happy to help.
> 
> You can't send UDP or DTLS traffic directly unfortunately.

I want to get my own udp addr and port through webrtc, and then notify another node through p2p. Similarly, the other node is the same, so that both nodes know each other's ip and port, and can establish kcp

@Sean-Der Thanks

**Comment by Sean-Der** [comment]
If you are ok with this only working with Pion you could do something like https://github.com/Sean-Der/pion-webrtc-shared-socket

That gives you access to the socket directly on each side. You can establish a WebRTC connection.

Then you can call `Send` on the socket with your outbound traffic. When it arrives you can intercept the traffic [here](https://github.com/Sean-Der/pion-webrtc-shared-socket/blob/master/main.go#L77) before it goes into `pion/webrtc`

**Comment by hktalent** [comment]
ok，thanks
