### ISSUE TITLE
Build error: package crypto/ecdh is not in GOROOT 

### ISSUE THREAD

**Issue by arunmir** [pion/example-webrtc-applications#134]
### Your environment.
  - Version: go version go1.15.15 linux/arm

### What did you do?

I am currently attempting to build the WebRTC example on Raspberry Pi OS. However, I encountered the following build error: "../../../../go/pkg/mod/golang.org/x/crypto@v0.11.0/curve25519/curve25519_go120.go:9:8: package crypto/ecdh is not in GOROOT (/usr/lib/go-1.15/src/crypto/ecdh)". It appears to be a dependency version mismatch error. Has anyone successfully resolved this issue previously?

**Comment by Sean-Der** [comment]
Hi @arunmir 

Would you mind upgrading to a modern version of Go? I believe you will need at least 1.18+ 

thanks for using Pion! Please re-open if you have more questions
