### ISSUE TITLE
Making a screen sharing example via Android

### ISSUE THREAD

**Issue by KMACEL** [pion/example-webrtc-applications#14]
## Summary

The "gstreamer-receive" application is sharing screenshots for desktops, but sharing only cameras on Android devices. The screen sharing app on Android devices can be nice.

**Comment by Sean-Der** [comment]
Hey @KMACEL 

I updated the examples to also include [getDisplayMedia](https://github.com/pion/example-webrtc-applications/blob/master/gstreamer-receive/jsfiddle/demo.js#L56)

thanks for using Pion :)
