### ISSUE TITLE
SFU-WS returns Incoming unhandled RTP ssrc(2333161655), OnTrack will not be fired. mid RTP Extensions required for Simulcast, when running the code on browser

### ISSUE THREAD

**Issue by KedwithGod** [pion/example-webrtc-applications#168]
### Your environment.
  - Version: *Release or SHA*
  - Browser: *include version*
  - Other Information - *stacktraces, related issues, suggestions how to fix, links for us to have context*

**Comment by Embiggenerd** [comment]
I am getting the same problem, but only with chrome on my mac m1. Browser is receiving infinite offer signals. 

Strangely, if I first connect with safari, chrome then joins without a problem. Only when chrome is the first peerConnection.

**Comment by Sean-Der** [comment]
Hey @KedwithGod @Embiggenerd 

This has been fixed! Thanks for the bug report. This repo now uses v3.2.32 that doesn't have the issue

Chrome when answering to a recvonly transceiver will not send a `a=ssrc` with the MSID. If you are doing multi-track this is noticeable. 

A workaround exists and was added to Pion. See https://issues.chromium.org/u/1/issues/328522463?pli=1

**Comment by KedwithGod** [comment]
thank @Sean-Der i will checked that
