### ISSUE TITLE
sfu-ws subscriber example doesn't work on mobile browsers: safari and google chrome

### ISSUE THREAD

**Issue by Demuzx** [pion/example-webrtc-applications#20]
sfu-ws subscriber example doesn't work on mobile browsers: safari and google chrome

![mobile](https://user-images.githubusercontent.com/30521627/58173748-93140b80-7cb5-11e9-9f47-907057356e60.png)

![IMG_0034](https://user-images.githubusercontent.com/30521627/58173851-da020100-7cb5-11e9-85a4-89b8acf52637.PNG)

**Comment by nkev** [comment]
The issue also exists with audio-only broadcasting. It works fine on all my windows and macbook desktop browsers: Chrome/Firefox/Safari have no issue in any combination of publish/subscribe. 

But mobile browsers are the opposite. I've been trying for days now and I cannot get any IOS or Android phone, iPad Pro or Samsung Android tablet to publish or subscribe Opus audio via HTTP (localhost) or HTTPS on LAN or Internet. On HTTP/LAN the mobile browsers simply do nothing when buttons clicked.  On HTTPS/Internet (AWS server), I get the following from all IOS/Android mobile browsers including Firefox, Chrome and Safari (latest versions):

```http: TLS handshake error from xxx.xxx.xxx.xxx:65291: remote error: tls: unknown certificate```

My SSL certificate is a purchased wildcard RapidSSL. My code is simply the Pion SFU example but adjusted for Opus audio. The frustraing thing is all desktop browsers work fine as both publisher or subscriber. Is there a Pion opus based audio broadcasting example anyone knows of? I'm now going to try datachannels on mobile browsers to see if that works.

**Comment by six519** [comment]
Subscribe doesn't work on Safari MacBook Pro but publish works fine.

My Safari Version: 14.0 (15610.1.28.1.9, 15610)

**Comment by Sean-Der** [comment]
This is fixed!

In pion/webrtc@v2 we expected users to handle PayloadTypes. Now that I have upgraded to /v3 SSRC/PayloadTypes are chosen at runtime and things just work.

Sorry for the bugs, and thanks for using Pion!
