### ISSUE TITLE
github.com/pion/webrtc/v2 404

### ISSUE THREAD

**Issue by funnywwh** [pion/example-webrtc-applications#21]
github.com/pion/webrtc/v2 not found

**Comment by Sean-Der** [comment]
Hi @funnywwh 

Thanks for using Pion. Are you using a version of Go that supports modules, and is it enabled?

What are you doing to get this error?

thanks!

**Comment by Sean-Der** [comment]
@funnywwh I am also happy to help on [Slack](https://pion.ly/slack)

thanks for using Pion! And if there is anything else I can do feel free to reach out.
