### ISSUE TITLE
mDNS: failed to join multicast group goroutine 299

### ISSUE THREAD

**Issue by Stunext** [pion/example-webrtc-applications#27]
### Your environment.
  - Version: Ubuntu 18 in WSL
  - Browser: Chrome 77.0.3865.90

### What did you do?
-Run the server
-Go to browser and publish

Then in other PC via local network
-Go to browser and subscribe

### What did you expect?
-The video and audio from the publisher

### What happened?
-Nothing happen
-Error: mDNS: failed to join multicast group goroutine 299

**Comment by Sean-Der** [comment]
@Stunext 

I am not familiar with the networking stack in WSL, but it sounds like it doesn't implement everything we need.

Pion should work on Windows, we don't require any C code! Would you mind trying the program directly on Windows (and not in WSL)?

thanks

**Comment by Stunext** [comment]
I tried and now no more errors appears but is the same... nothing happen and the only log in the console is: http: TLS handshake error from 192.168.0.10:40707: remote error: tls: unknown certificate

**Comment by master-hax** [comment]
@Stunext also running into this with Ubuntu 20 in WSL, what did you do to make it work?
