### ISSUE TITLE
gstreamer-receive example not working

### ISSUE THREAD

**Issue by JibinNajeeb** [pion/example-webrtc-applications#47]
In jsfiddle.net text areas are showing empty. There is nothing to copy as mentioned in the readme section

**Comment by Sean-Der** [comment]
Hey @JibinNajeeb, sorry for the delay!

Sorry for the delay, can you try removing STUN from your iceServers list? If you are in a restricted network it will take 30 seconds for the `jsfiddle.net` entries to be populated.

**Comment by Sean-Der** [comment]
@JibinNajeeb if you are still having issues please re-open! Resolving as stale for now.
