### ISSUE TITLE
janus-gateway example

### ISSUE THREAD

**Issue by kqbi** [pion/example-webrtc-applications#49]
how to go build janus-gateway example for windows

**Comment by Sean-Der** [comment]
Hey @kqbi 

If you run `go build` in the directory it will build the binary. What have you tried so far? Do you have any error messages/logs?

thanks for using Pion!

**Comment by kqbi** [comment]
pacman -S mingw-w64-x86_64-gstreamer mingw-w64-x86_64-gst-libav mingw-w64-x86_64-gst-plugins-good mingw-w64-x86_64-gst-plugins-bad mingw-w64-x86_64-gst-plugins-ugly
