### ISSUE TITLE
janus-gateway  videoroom  demo

### ISSUE THREAD

**Issue by kqbi** [pion/example-webrtc-applications#50]
![图片](https://user-images.githubusercontent.com/40823194/82622144-a121a280-9c0f-11ea-8df1-7e8eed2ba5ee.png)
![图片](https://user-images.githubusercontent.com/40823194/82622308-05dcfd00-9c10-11ea-95e2-e536b84f4759.png)

On the right is demo. Is this normal? If it's normal, how to achieve the effect on the left。

**Comment by Sean-Der** [comment]
Hi @kqbi 

I have never tried it in Windows, so not sure what is going wrong. It looks like it is failing the load all your GStreamer plugins (not sure why). What does the message after the path say?

Maybe if you do `GST_DEBUG` it could also have more information?

**Comment by Sean-Der** [comment]
Resolving as stale.

@kqbi if I can be more help please re-open. thanks!
