### ISSUE TITLE
Add example of WebRTC -> HLS

### ISSUE THREAD

**Issue by mohit810** [pion/example-webrtc-applications#60]
Hi, If possible can any one give me guidance for creating live streaming server that receives the broadcast from android/ios/webbrowser and then convert the stream into different quality for delivering to users by using Hls. I know the broadcasting and receiving parts that involves the clients, but need guidance in the server part.

The Flow is:
Android/ios/web browser (single user) ---- Broadcast ----> Server ---- Broadcast(hls) ----> Android/ios/Web browser
Server - Receive and change format to hls, create multiple quality of the video than broadcast to multiple users(1:N relation)

**Comment by mohit810** [comment]
> Hey @mohit810
> 
> Would love to help! If you ok with this being Open Source I am happy to help you wire this up for. We can put the code in https://github.com/pion/example-webrtc-applications
> 
> I would check out this answer https://stackoverflow.com/questions/63516782/ffmpeg-live-stream-transcoding-a-v-sync-issues-on-fast-camera-movement this user already has it working, might be some good hints.

Yeah sure, though contribution from my end may be slow due to day job and also me being a fresher. Other than that I am happy to help in anyway possible. (side-note :- I am new to the developing as i started to Dev. journey in January. I am eager to learn new tech. and concepts.)

**Comment by Sean-Der** [comment]
@mohit810 has started a project for this! https://github.com/mohit810/streamingcdn I will put in example-webrtc-applications when we announce it :)

**Comment by trickpattyFH20** [comment]
Any updates on adding an example of this? @Sean-Der
