### ISSUE TITLE
sfu-ws not trigger event OnTrack

### ISSUE THREAD

**Issue by seta-sonvt** [pion/example-webrtc-applications#66]
I create simple publisher client that send rtsp stream data to sfu-ws signaling server, but OnTrack event in sfu-ws is not triggered.

SFU-WS log:

![Screenshot from 2020-10-20 14-12-30](https://user-images.githubusercontent.com/58415957/96552900-9bbfa580-12de-11eb-8054-e4ea7ec613e4.png)

Client Log:
![Screenshot from 2020-10-20 14-12-51](https://user-images.githubusercontent.com/58415957/96552929-a417e080-12de-11eb-9e11-ccabd5a33146.png)

Here my code: 
[rtsp-client.zip](https://github.com/pion/example-webrtc-applications/files/5406872/rtsp-client.zip)

**Comment by Sean-Der** [comment]
This is fixed!

In `pion/webrtc@v2` we required the user to handle PayloadTypes/SSRC. In /v3 we mange these internally.

I also simplified the `sfu-ws` example. If you are still having issues please re-open. Thanks for using Pion!
