### ISSUE TITLE
Duplicated code on gstreamer-receive

### ISSUE THREAD

**Issue by PhVHoang** [pion/example-webrtc-applications#70]
I see those lines of code (from line 38 to line 42) have duplicated code. I don't understand whether the duplicated part serves for a specific purpose but it seems that this is not necessary. 

https://github.com/pion/example-webrtc-applications/blob/master/gstreamer-receive/main.go#L38

**Comment by Sean-Der** [comment]
@PhVHoang If you want to make a PR, those lines can be deleted!

In early versions of Pion you needed to explicitly create a transceiver for everything you were willing to receive. In newer versions answerers accept all the offered tracks.

**Comment by Sean-Der** [comment]
Fixed with 8ce788562c2b1e012e3c07665de045f7415cc719

Thank you so much @PhVHoang !
