### ISSUE TITLE
Migrate to pion/webrtc@v3

### ISSUE THREAD

**Issue by Moisesbr** [pion/example-webrtc-applications#72]
I tried adapt these examples for v3 using notes writen by @Sean-Der https://github.com/pion/webrtc/wiki/Release-WebRTC@v3.0.0 , but I'm struggling with `gst.CreatePipeline` to which depends `internal/gstreamer-src` and apparently had a some changes to do.
Thanks.

**Comment by Sean-Der** [comment]
@Moisesbr that would be amazing! The API for `pion/webrtc@v3` is complete, I am just working on closing some final bugs.

Feel free to migrate one example at a time :) 

Also when `v3.0.0` I plan on migrating popular projects that import Pion. It will help me understand any oversights I made etc..

**Comment by Moisesbr** [comment]
here is my fork for testing purposes, https://github.com/Moisesbr/example-webrtc-applications/commit/92ee9b5043e635d32ec967fcf234dd9bf9986d8d my first change example `gstreamer-send` is not working the sound, running with v2 dependencies work fine, probably I'm missing something, could please give the right direction?

**Comment by Sean-Der** [comment]
Hey @Moisesbr 

I am ready to take this on. You want to open a PR with your work so far :) I tagged `v3.0.0` so now is a great time to do this.

**Comment by Sean-Der** [comment]
Fixed with 36cc229b8002db5e9fc4cf04d923e5bda69b7106
