### ISSUE TITLE
Stream Webcam video to janus

### ISSUE THREAD

**Issue by pouryajafarzadeh** [pion/example-webrtc-applications#85]
I could connect to the janus video room successfully with your example, but is it possible to send the webcam (or video file) with audio to the janus video room? Could you put its code in golang please?

**Comment by Sean-Der** [comment]
Hey @pouryajafarzadeh 

https://github.com/pion/example-webrtc-applications/tree/master/janus-gateway/video-room demonstrates how to send media in. You could modify it so the Tracks are fed from a video file link https://github.com/pion/webrtc/blob/master/examples/play-from-disk/main.go#L49 if you wanted.

**Comment by pouryajafarzadeh** [comment]
@Sean-Der 
Thank you for your guides, I could run a local video on the webpage, but I should try to send it to Janus.
