### ISSUE TITLE
sfu-ws - Safari Issue

### ISSUE THREAD

**Issue by oddimportance** [pion/example-webrtc-applications#89]
### Your environment.
  - OS: Ubuntu 18 with Nginx
  - Version: webrtc V3
  - Browser: Safari 13.1.2

### What did you do?
Installed sfu-ws on a remote server. Here is the live version: [my remote server](https://sfu-ws.zama-syed.com)

### What did you expect?
Basic cross-browser video conferencing

### What happened?
It worked like a charm on Chrome and Firefox but has its issues with Safari (both osx and ios). Please note Chrome perfect on osx, but is not supported on ios.
It seems that this is quite a known issue. I found articles and Bug reports claiming the problem to be with lack of Saffari's support for VP8.
Although there were no particular panics or warnings, yet every now and then is see the following error:
`pc ERROR: 2021/02/11 13:42:50 Incoming unhandled RTP ssrc(741086092), OnTrack will not be fired. stream id RTP Extensions required for Simulcast`
`pc ERROR: 2021/02/11 13:24:26 Incoming unhandled RTP ssrc(1168873309), OnTrack will not be fired. incoming SSRC failed Simulcast probing`

However, Safari triggers onTrack and adds a video element, but no stream is played on the added video element. Whereas Chrome or Firefox do not fire onTrack, when streamed from Safari. Hence, no video element is added to the remote-videos sector.

Should it be of interest, I can provide the Nginx Site-Config file.

Any idea where I'm going wrong?

Thanks in advance.

PS: I had to add `wss` support on line 61 in main.go and in index.html to make it work remotely.

**Comment by Sean-Der** [comment]
Hey @oddimportance 

This is a mistake we made. Safari requires that codecs are upcased `VP8`, `VP9` and `H264` which we didn't do. I pushed a fixed to pion/webrtc and tagged `v3.0.8`

**Comment by oddimportance** [comment]
Hey Sean-Der,
lovely works perfect! Thanks for the prompt fix.
