### ISSUE TITLE
v4l2h264enc & omxh264enc didn't work,it seem to received,but can't decode.

### ISSUE THREAD

**Issue by cRuiTe** [pion/example-webrtc-applications#96]
@Sean-Der Thanks for the hint.

i change the code like:
pipelineStr = pipelineSrc + " ! v4l2h264enc extra-controls=s,video_bitrate=2000000 ! video/x-h264,profile=constrained-baseline,level=(string)3.1 ! " + pipelineStr
or
pipelineStr = pipelineSrc + " ! omxh264enc control-rate=1 target-bitrate=1145000 ! " + pipelineStr

but it not work,the browser seem to received bytes,but can not decode...

browser webrtc log info:

Report type=inbound-rtp
id=RTCInboundRTPVideoStream_597189778
time=1617955656066.087
ssrc: 597189778
isRemote: false
mediaType: video
kind: video
trackId: RTCMediaStreamTrack_receiver_52
transportId: RTCTransport_0_1
codecId: RTCCodec_1_Inbound_102
firCount: 0
pliCount: 1680
nackCount: 0
packetsReceived: 37785
bytesReceived: 40068701
headerBytesReceived: 453420
packetsLost: 0
lastPacketReceivedTimestamp: 17640.963
framesReceived: 8525
framesPerSecond: 25
framesDecoded: 0
keyFramesDecoded: 140
framesDropped: 8474
totalDecodeTime: 0
totalInterFrameDelay: 0
totalSquaredInterFrameDelay: 0
decoderImplementation: FFmpeg

did i miss something?

Hey @cRuiTe 

Thanks for checking out Pion. The example is hardcoded to always use `x264enc` you can change the encoder [here](https://github.com/pion/example-webrtc-applications/blob/master/internal/gstreamer-src/gst.go#L58) 

Thanks for checking out Pion. If you run into anything else I am also available in [Slack](https://pion.ly/slack)

_Originally posted by @Sean-Der in https://github.com/pion/example-webrtc-applications/issues/95#issuecomment-817348140_

**Comment by cRuiTe** [comment]
#95 #

**Comment by Sean-Der** [comment]
Sorry I missed this, were you able to get it to work @cRuiTe ?

**Comment by cRuiTe** [comment]
yes,just update to the Latest... @Sean-Der
