### ISSUE TITLE
Can this lib support to receive rtsp by gocv and AI detect and cast a stream to webrtc or rtmp by ffmpeg?

### ISSUE THREAD

**Issue by skytodmoon** [pion/example-webrtc-applications#98]
Can this lib support to receive rtsp by gocv and AI detect and cast a stream to webrtc or rtmp by ffmpeg?

**Comment by Sean-Der** [comment]
Hi @skytodmoon 

Yes it can. You will need to handle the integrations but these are the steps I would take.

* Pull the RTSP using [RTSPtoWebRTC](https://github.com/deepch/RTSPtoWebRTC) or [gosrtplib](https://github.com/aler9/gortsplib)
* Run the frames through GoCV and then send the media back out. [gocv-receive](https://github.com/pion/example-webrtc-applications/tree/master/gocv-receive) is an example of this.

Sorry for the delay on this. I am available to answer questions on [Slack](https://pion.ly/slack) or can respond here.

thanks!
